	var openId = JSON.parse( window.LS.get( 'shared' )||'{}' ).openId;

	//uat
	    var site = "http://mp.foresealife.com";
		var childLink = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx2a11f72e035ac858&redirect_uri=http%3a%2f%2fmp.foresealife.com%2felifeweb%2finsurance%2fchild%2fproductInfo.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
	    var jfThreeLink = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx2a11f72e035ac858&redirect_uri=http%3a%2f%2fmp.foresealife.com%2felifeweb%2finsurance%2finvest%2fjfthreeInfo.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
	    var jfFourLink = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx2a11f72e035ac858&redirect_uri=http%3a%2f%2fmp.foresealife.com%2felifeweb%2finsurance%2finvest%2fjffourInfo.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
	    var loveLink = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx2a11f72e035ac858&redirect_uri=http%3a%2f%2fmp.foresealife.com%2felifeweb%2finsurance%2flove%2fpublicity.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
	    var zcbLink = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx2a11f72e035ac858&redirect_uri=http%3a%2f%2fmp.foresealife.com%2felifeweb%2finsurance%2fzcb%2fzcbProject.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
	    var clientLink = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx2a11f72e035ac858&redirect_uri=http%3a%2f%2fmp.foresealife.com%2felifeweb%2fclient%2factivity.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
	    var wxclaimUrl = "http://183.62.139.34:8083/wxclaim/case/claimPage.do?openId=";
	    var groupUrl = "http://mp.foresealife.com/product/groupInsurance/index.html";
	    var wxactivity ="https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx2a11f72e035ac858&redirect_uri=http%3a%2f%2fmp.foresealife.com%2felifeweb%2fgift%2findex.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
	    var directreceive = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx2a11f72e035ac858&redirect_uri=http%3a%2f%2fmp.foresealife.com%2felifeweb%2fdirectreceive%2findex.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
    	var wxspread = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx2a11f72e035ac858&redirect_uri=http%3a%2f%2fmp.foresealife.com%2factivityweb%2fspread%2findex.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
    	var festival = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx2a11f72e035ac858&redirect_uri=http%3a%2f%2fmp.foresealife.com%2factivityweb%2ffestival%2findex.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
    	var gohomelink = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx12a9ea750ab8e849&redirect_uri=http%3a%2f%2fmp.foresealife.com%3a8080%2factivityweb%2flx_activity%2findex.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
    //product
/*    var site = "http://shop.foresealife.com";     
    var childLink = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx58324bcceb2b1204&redirect_uri=http%3a%2f%2fshop.foresealife.com%2felifeweb%2finsurance%2fchild%2fproductInfo.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
    var jfThreeLink = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx58324bcceb2b1204&redirect_uri=http%3a%2f%2fshop.foresealife.com%2felifeweb%2finsurance%2finvest%2fjfthreeInfo.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
    var jfFourLink = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx58324bcceb2b1204&redirect_uri=http%3a%2f%2fshop.foresealife.com%2felifeweb%2finsurance%2finvest%2fjffourInfo.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
    var loveLink = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx58324bcceb2b1204&redirect_uri=http%3a%2f%2fshop.foresealife.com%2felifeweb%2finsurance%2flove%2fpublicity.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
    var zcbLink = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx58324bcceb2b1204&redirect_uri=http%3a%2f%2fshop.foresealife.com%2felifeweb%2finsurance%2fzcb%2fzcbProject.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
	var clientLink = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx58324bcceb2b1204&redirect_uri=http%3a%2f%2fshop.foresealife.com%2felifeweb%2fclient%2factivity.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
	var wxclaimUrl = "http://183.62.194.189:8081/wxclaim/case/claimPage.do?openId=";
	var groupUrl = "http://m.foresealife.com/product/groupInsurance/index.html";
	var wxactivity = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx58324bcceb2b1204&redirect_uri=http%3a%2f%2fshop.foresealife.com%2felifeweb%2fgift%2findex.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
	var directreceive = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx58324bcceb2b1204&redirect_uri=http%3a%2f%2fshop.foresealife.com%2felifeweb%2fdirectreceive%2findex.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
	var wxspread = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx58324bcceb2b1204&redirect_uri=http%3a%2f%2fshop.foresealife.com%2factivityweb%2fspread%2findex.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
	var festival = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx58324bcceb2b1204&redirect_uri=http%3a%2f%2fshop.foresealife.com%2factivityweb%2ffestival%2findex.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";
	var gohomelink = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx58324bcceb2b1204&redirect_uri=http%3a%2f%2fshop.foresealife.com%2factivityweb%2flx_activity%2findex.html%3frecommendId%3d"+openId+"&response_type=code&scope=snsapi_base&state=openId#wechat_redirect";*/